### PR TITLE
Added Image Description Feature

### PR DESCRIPTION
**Pull request by binayshaw7777**
Added Image Description Feature

### CODE REVIEW

**Review by vilgad — CHANGES_REQUESTED** [review]
You have done a good job but we are using fragments in the app so use fragment for image description

**Comment by binayshaw7777** [comment]
I'm really sorry, I don't know kotlin that much as well as fragments. :(

**Comment by binayshaw7777** [comment]
Hey @vilgad instead can you create another issue to shift activity to fragment? Others might complete this.

**Comment by vivekgupta4Git** [comment]
I m up

**Pull request closed without merging**
