### PR TITLE
6

### PR DESCRIPTION
**Pull request by vivekgupta4Git**
Solved the issue. This is my first contribution ever on github.

### CODE REVIEW

**Comment by vilgad** [comment]
> Solved the issue. This is my first contribution ever on github.

hey its good you are starting your first contribution with our project, but are you contributing for JWOC?

if yes, 
1) you should ask the owner to assign the issue to you 
2) mentee's can start contribution from 1st feb

Happy Coding ;)

So for now i am closing your request without merging it

**Comment by vivekgupta4Git** [comment]
Well, I didn't know much about how to contribute and where to contribute. I am in learning phase.

**Comment by vilgad** [comment]
> Well, I didn't know much about how to contribute and where to contribute. I am in learning phase.

No need to worry, if you come across any project of JWOC then first bond with the mentors and other members 

You can clear all your doubts with them. They will guide you 

SO for now the community bonding period is going on so connect with mentors on the respective discord channel and start your contribution from 1st feb

Happy Coding ;)

**Comment by vivekgupta4Git** [comment]
Btw, what is Jwoc?

**Comment by vilgad** [comment]
Sorry for the late reply

JWOC is an open source program which is similar to the big open source
program GSOC. Through these programs you can start your open source
journey, here you can network with other people and can make great bond
with mentors, they will help you in your open source journey and will also
clear your doubts. You will learn a lot from these programs so do
participate

Spread Love and Happy Coding ;)

**Pull request closed without merging**
